name: mock_web_server
version: 5.0.0-nullsafety.1
description: Versatile scriptable Web Server for real integration tests in Flutter, server, and Dart CLI applications 
author: Miguel Castiblanco <miguel@starcarr.co>
homepage: https://git.starcarr.co/Dart/MockWebServer

dev_dependencies:
  test: '>=1.5.1 <2.0.0'

environment:
  sdk: '>=2.12.0 <3.0.0'
